### ISSUE TITLE
Error with cargo install

### ISSUE THREAD

**Issue by josejachuf** [pjsier/echomap#141]
Hi. 

rustc --version
rustc 1.68.2 (9eb3afe9e 2023-03-27)

When I try to install the app charge I get this error:

`$ cargo install echomap`

> Compiling echomap v0.7.2
> error[E0631]: type mismatch in function arguments
>    --> /home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:146:18
>     |
> 146 |             .map(GeoJson::FeatureCollection)
>     |              --- ^^^^^^^^^^^^^^^^^^^^^^^^^^
>     |              |   |
>     |              |   expected due to this
>     |              |   found signature defined here
>     |              required by a bound introduced by this call
>     |
>     = note: expected function signature `fn(geojson::feature_collection::FeatureCollection) -> _`
>                found function signature `fn(geojson::FeatureCollection) -> _`
> note: required by a bound in `std::iter::Iterator::map`
>    --> /home/jose/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:785:12
>     |
> 785 |         F: FnMut(Self::Item) -> B,
>     |            ^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Iterator::map`
> 
> error[E0599]: the method `flat_map` exists for struct `Map<FilterMap<Map<IntoIter<String>, [closure@main.rs:144:18]>, [closure@main.rs:145:25]>, fn(FeatureCollection) -> GeoJson {FeatureCollection}>`, but its trait bounds were not satisfied
>    --> /home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:147:14
>     |
> 147 |             .flat_map(|g| process_geojson(g, simplification, is_area))
>     |              ^^^^^^^^ method cannot be called due to unsatisfied trait bounds
>     |
>    ::: /home/jose/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:61:1
>     |
> 61  | pub struct Map<I, F> {
>     | -------------------- doesn't satisfy `_: Iterator`
>     |
>     = note: the following trait bounds were not satisfied:
>             `<fn(geojson::FeatureCollection) -> GeoJson {FeatureCollection} as FnOnce<(geojson::feature_collection::FeatureCollection,)>>::Output = _`
>             which is required by `Map<FilterMap<Map<std::vec::IntoIter<std::string::String>, [closure@/home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:144:18: 144:21]>, [closure@/home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:145:25: 145:28]>, fn(geojson::FeatureCollection) -> GeoJson {FeatureCollection}>: Iterator`
>             `fn(geojson::FeatureCollection) -> GeoJson {FeatureCollection}: FnMut<(geojson::feature_collection::FeatureCollection,)>`
>             which is required by `Map<FilterMap<Map<std::vec::IntoIter<std::string::String>, [closure@/home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:144:18: 144:21]>, [closure@/home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:145:25: 145:28]>, fn(geojson::FeatureCollection) -> GeoJson {FeatureCollection}>: Iterator`
>             `Map<FilterMap<Map<std::vec::IntoIter<std::string::String>, [closure@/home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:144:18: 144:21]>, [closure@/home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:145:25: 145:28]>, fn(geojson::FeatureCollection) -> GeoJson {FeatureCollection}>: Iterator`
>             which is required by `&mut Map<FilterMap<Map<std::vec::IntoIter<std::string::String>, [closure@/home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:144:18: 144:21]>, [closure@/home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/echomap-0.7.2/src/main.rs:145:25: 145:28]>, fn(geojson::FeatureCollection) -> GeoJson {FeatureCollection}>: Iterator`
> 
> Some errors have detailed explanations: E0599, E0631.
> For more information about an error, try `rustc --explain E0599`.
> error: could not compile `echomap` due to 2 previous errors
> error: failed to compile `echomap v0.7.2`, intermediate artifacts can be found at `/tmp/cargo-installmIbOn6`

**Cloning the repository, compile correctly**

**Comment by pjsier** [comment]
@josejachuf thanks for the report! This should be fixed with version 0.7.3. I was able to reproduce the original issue and now running `cargo install echomap` completes. Let me know if you're still seeing the issue

**Comment by josejachuf** [comment]
@pjsier this works fine! Thanks
